### PR TITLE
Add Standard Spanish

### PR DESCRIPTION
**Pull request by elifoster**
Create new Spanish translation for general Spanish based on es-ni.json. I have converted all uses of voseo to tuteo, which most (if not all) other Spanish speaking countries use.

### CODE REVIEW

**Comment by elifoster** [comment]
So, uh, it's been over a month. I'm going to merge this because it's literally just a translation fix.

**Comment by Alexia** [comment]
That is fine.  We lost 2/3 team members here at Gamepedia in the past couple weeks so I am picking up the pieces of what was being worked on by everyone.  I put in a note to get this merged in for the deploy on Wednesday.

**Comment by elifoster** [comment]
No worries.

**Comment by Alexia** [comment]
I have this merged in for the Wednesday deploy.

**Pull request merged**
